
import java.util.ArrayList;
import javax.swing.JOptionPane;



/** Programmer: Ayesha Arshad
 *
 * @author hhhgo
 */
public class AirlinePoints extends javax.swing.JFrame {

    //creates an arrayList of objects. The objects are defined by the airlinePoints class
    ArrayList <airlinePoints> points = new ArrayList<>(); 
    
    /**
     * Creates new form AirlinePoints
     */
    public AirlinePoints() {
        initComponents();
    }
 
/**This section sets up the new object with field names and values when called as a new object. **/      
    class airlinePoints { 
        String firstName, lastName, week1, week2, week3, week4;
        airlinePoints (String _firstName, String _lastName,String _week1, String _week2, String _week3, String _week4){
            week1 = _week1;
            lastName = _lastName;
            week2 = _week2;
            week3 = _week3;
            firstName = _firstName;
            week4 = _week4; 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstNameLabel2 = new javax.swing.JLabel();
        firstNameinput = new javax.swing.JTextField();
        lastNameLabel2 = new javax.swing.JLabel();
        lastNameinput = new javax.swing.JTextField();
        week1Label2 = new javax.swing.JLabel();
        week1Input = new javax.swing.JTextField();
        week2Label2 = new javax.swing.JLabel();
        week2Input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        week3Input = new javax.swing.JTextField();
        week4Label3 = new javax.swing.JLabel();
        week4Input = new javax.swing.JTextField();
        Addbutton = new javax.swing.JButton();
        listButton1 = new javax.swing.JButton();
        totalPointsButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pointsOutput = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jLabel1.setText("Airline Points");

        firstNameLabel2.setText("First Name: ");

        lastNameLabel2.setText("Last Name: ");

        week1Label2.setText("Week 1: ");

        week2Label2.setText("Week 2:");

        jLabel2.setText("Week 3:");

        week4Label3.setText("Week 4: ");

        Addbutton.setText("Add");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        listButton1.setText("List");
        listButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButton1ActionPerformed(evt);
            }
        });

        totalPointsButton1.setText("Total Points");
        totalPointsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPointsButton1ActionPerformed(evt);
            }
        });

        pointsOutput.setColumns(20);
        pointsOutput.setRows(5);
        jScrollPane1.setViewportView(pointsOutput);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(listButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(week1Label2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(week1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(week2Label2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(week2Input))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(week4Label3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(week3Input)
                                            .addComponent(week4Input)))
                                    .addComponent(totalPointsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(firstNameLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(firstNameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastNameLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastNameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exit))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel2)
                    .addComponent(firstNameinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel2)
                    .addComponent(lastNameinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(week1Label2)
                            .addComponent(week1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(week2Label2)
                            .addComponent(week2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(week3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(week4Label3)
                            .addComponent(week4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalPointsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
   public void add() { //method to add user input to array
       
       airlinePoints c; // variable “c” sends the input information to the class.  
       String firstName, lastName, week1, week2, week3, week4;  
       int num1, num2, num3, num4; 
   
     /**Sorts user inputs to their appropriate variables **/   
     firstName = firstNameinput.getText(); 
     lastName = lastNameinput.getText(); 
    
  try { //try..catch to prevent the user from entering letters for points input
 
  /**Points input changed to integers */    
    num1 = Integer.parseInt(week1Input.getText());
    num2 = Integer.parseInt(week2Input.getText());
    num3 = Integer.parseInt(week3Input.getText());
    num4 = Integer.parseInt(week4Input.getText());
 
 /**If structure runs when points input does not equal a number. The opposite of what we want is coded.(It works that way).
  If structure also only runs when points are greater than or equal to 0 */  
    if ((!week1Input.getText().equals(num1)|| week2Input.getText().equals(num2) || week3Input.getText().equals(num3) || week4Input.getText().equals(num4))&& (num1 >=0 && num2>=0 && num3>=0&& num4>=0)) {    
  
   /**Sorts user inputs to their appropriate variables **/
     week1 = week1Input.getText(); 
     week2 = week2Input.getText(); 
     week3 = week3Input.getText();  
     week4 = week4Input.getText(); 
     c = new airlinePoints(firstName, lastName, week1, week2, week3, week4);
       points.add(c); //class is added to the points ArrayList
    }
    
  } catch (Exception e) {
      pointsOutput.setText("Numbers must be used for points"); // message is displayed when points have letters
     
      
  }
   }
   
       
    
    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
     add(); //calls add method
        
    }//GEN-LAST:event_AddbuttonActionPerformed
 public void list() { //method to list airline points data and passengers
     String temp = ""; 
    
    /**The get(x) portion of the code goes to the “x” index of the ArrayList,
      * then looks for the value in the field defined by the object class. **/ 
     for (int x=0; x<=points.size()-1;x++) {
         temp = temp + points.get(x).firstName + " "
                 + points.get(x).lastName + " "
                 + points.get(x).week1 + " "
                 + points.get(x).week2 + " "
                 + points.get(x).week3 + " "
                 + points.get(x).week4 + "\n";
     }
     pointsOutput.setText(temp); //outputs the list of passenger points in the arraylist
         
 }
         
    private void listButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButton1ActionPerformed
       
        list(); // calls list method
    }//GEN-LAST:event_listButton1ActionPerformed
  public void totalPoints() { //method for total points and bonus
    int total = 0; 
    int bonus = 0; 
   
    for (int i=0; i<=points.size()-1;i++) { 
        
     //if structure runs when the user's input for firstname and lastname match the data in the arraylist
     if ((firstNameinput.getText().equals(points.get(i).firstName)) && (lastNameinput.getText().equals(points.get(i).lastName))) { 
 
       /**Points are converted to integers */    
         int point1 = Integer.parseInt(points.get(i).week1);
         int point2 = Integer.parseInt(points.get(i).week2);
         int point3 = Integer.parseInt(points.get(i).week3);
         int point4 = Integer.parseInt(points.get(i).week4);
        total = point1 + point2 + point3 + point4; //points are added
        
        if (total > 5000) { //if total is greater than 5000 points, than passenger gets bonus 1000 points
            bonus = 1000; 
            
       /**These messages are displayed if user is qualified or not*/      
          JOptionPane.showMessageDialog(null,points.get(i).firstName + " you have qualified for 1000 bonus points!");
        } else
            JOptionPane.showMessageDialog(null,points.get(i).firstName + " you have not qualified for 1000 bonus points");
          
     } 
    } 
      pointsOutput.setText("Total is: " + total + " Bonus: " + bonus); //message displayed
            
  }
       
    private void totalPointsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPointsButton1ActionPerformed
        totalPoints(); //calls total points method
    }//GEN-LAST:event_totalPointsButton1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0); //stops running the program
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlinePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlinePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlinePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlinePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlinePoints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton exit;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JTextField firstNameinput;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JTextField lastNameinput;
    private javax.swing.JButton listButton1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTextArea pointsOutput;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton totalPointsButton1;
    private javax.swing.JTextField week1Input;
    private javax.swing.JLabel week1Label2;
    private javax.swing.JTextField week2Input;
    private javax.swing.JLabel week2Label2;
    private javax.swing.JTextField week3Input;
    private javax.swing.JTextField week4Input;
    private javax.swing.JLabel week4Label3;
    // End of variables declaration//GEN-END:variables

}
